### PR TITLE
Fixed 2 errors in project from using dot notation when class couldn't

### PR DESCRIPTION
**Pull request by andrewcar**
...be inferred

### CODE REVIEW

**Comment by GJNilsen** [comment]
I would have changed it from
@IBInspectable public var strokeColor = UIColor.black
to
@IBInspectable public var strokeColor: UIColor = .black

Suggest you change it so I can merge the pull request :)
And remove the project files please.

**Comment by andrewcar** [comment]
That's better - fixed!

**Comment by andrewcar** [comment]
Sorry I forgot to remove the project files. 

You should use a .gitignore.

**Comment by GJNilsen** [comment]
Yah, I probably should. Back when I started the project, I knew close to nothing regarding git and GitHub..

**Pull request merged**
