### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by sssbohdan**
Removed excessive "self.",
added formatting according to swift style guideline,
added early exit for "touchBegan" and "touchMoved".

### CODE REVIEW

**Comment by GJNilsen** [comment]
To what guideline are you adhering to? And please resolve or find the reason for the conflict. I do not have the time to check out conflicts in the branch when someone has a pull request.

**Comment by sssbohdan** [comment]
@GJNilsen https://github.com/raywenderlich/swift-style-guide.

**Comment by GJNilsen** [comment]
I was afraid you would mention the wenderlich one. Since I did not specify what style guide to adhere to, the blame is on me for that ;) Well, Ill accept the request when I get back from vacation, in the mean time I should probably write something regarding contribution and style guide and stuff like that.. Anyway, nice job.

**Comment by sssbohdan** [comment]
Also want to add, that there is no need to unwrap `delegate` just to invoke method. 
You can just write `delegate?.methodCall()` the result will be the same. It's hard for me to describe this more precisly because of  my english skill, therefore i just put link :). 
“Optional chaining is a process for querying and calling properties, methods, and subscripts on an optional that might currently be nil. If the optional contains a value, the property, method, or subscript call succeeds; if the optional is nil, the property, method, or subscript call returns nil. Multiple queries can be chained together, and the entire chain fails gracefully if any link in the chain is nil.”

Excerpt From: Apple Inc. “The Swift Programming Language (Swift 3.1).” iBooks. https://itun.es/ua/jEUH0.l

**Comment by sssbohdan** [comment]
@GJNilsen Please review and merge, i have fixed some logic problems in your code.

**Comment by GJNilsen** [comment]
I have reviewed the pull request, and cant approve a merge. You do have some valid points, while others are not. Im still not able to do any work on the class, my only device during the vacation is my iPhone, but as fast Im back, Ill draft a pull request that incorporates the lines that are acceptable. If you need to discuss this further please contact me on my email.

**Comment by sssbohdan** [comment]
@GJNilsen Okay, when I'll have some free time, I ll more precisely describe changes that I made in code and send you by email.

**Comment by sssbohdan** [comment]
@GJNilsen What issues? Branch does not have conflicts right now.

**Pull request closed without merging**
